### ISSUE TITLE
observe.py using a lot of CPU

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_exploration#12]
When running exploration it looks as if activity_observation observe.py is using a lot of CPU which is probably unnecessary (and adds to heat and power draw). 
![screenshot from 2016-05-05 22 11 24](https://cloud.githubusercontent.com/assets/927289/15057397/70536b54-130e-11e6-9c6f-b0a76121fbd9.png)

**Comment by ferdianjovan** [comment]
Ok, I will look into that.

**Comment by ferdianjovan** [comment]
This issue has been solved for a while.
