### ISSUE TITLE
build failure due to missing dependency soma manager 

### ISSUE THREAD

**Issue by santosj** [strands-project/strands_exploration#9]
Currently, the activity exploration depends on the soma manager  which is not released yet.

**Comment by ferdianjovan** [comment]
the activity exploration depends on soma_map_manager and soma_manager from SOMA 2.0

**Comment by marc-hanheide** [comment]
Well [soma](https://github.com/strands-project/soma) is released, but I'm not sure what SOMA 2.0 would be...

**Comment by ferdianjovan** [comment]
Is there a way to release what the branch has? soma_map_manager is in branch 2.0 in soma package.

**Comment by marc-hanheide** [comment]
The question is if you need both versions? If not, why don't you merge it into the main branch and just trigger a rerelease? That of course requires everybody to use the new version, but having two different incompatible ones would be a mess anyway.

**Comment by ferdianjovan** [comment]
I, myself, don't need both versions as I already use the newer version.
Ok, I will open an issue in Soma package regarding this.

**Comment by marc-hanheide** [comment]
That's now solved. Now it fails due to missing dependencies:

https://lcas.lincoln.ac.uk/jenkins/job/devel-indigo-strands_exploration/22/console

```
-- Could not find the required component 'image_transport'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "image_transport"
  with any of the following names:

    image_transportConfig.cmake
    image_transport-config.cmake

  Add the installation prefix of "image_transport" to CMAKE_PREFIX_PATH or
  set "image_transport_DIR" to a directory containing one of the above files.
  If "image_transport" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  monitored_vcs/spatiotemporal_exploration/CMakeLists.txt:4 (find_package)
```

**Comment by marc-hanheide** [comment]
But as this is now solved, please work on this new problem @santosj or @Jailander and I'll close this.

**Comment by santosj** [comment]
I will fix it tonight.
